config/routes.rb
Rails.application.routes.draw do

  resources :pages

  resources :livros

  root 'livros#index'

end

app/models/livro.rb
class Livro < ActiveRecord::Base

  has_many :pages, dependent: :destroy

  validates_presence_of :titulo
  validates_presence_of :autor
  validates_presence_of :editora

  mount_uploader :capa, CapaUploader

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :livro


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  PER_PAGE = 2
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json

  def index
    @livros = Livro.all.page(params[:page]).per(PER_PAGE).order('updated_at desc')
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro criado com sucesso.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :editora, :capa)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  PER_PAGE = 3
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all.page(params[:page]).per(PER_PAGE).order("updated_at desc")
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
    set_page
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Pagina cadastrada' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Pagina atualizada' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:data, :pagina, :livro_id, :livrocompleto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marcador</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "menu" %>
<%= yield %>

</body>
</html>

app/views/livros/_form.html.erb
<%= form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> não permitiram esse cadastro </h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, size: 50 %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_area :autor, rows:2, cols: 50 %>
  </div>
  <div class="field">
    <%= f.label :editora %><br>
    <%= f.text_field :editora, size: 50 %>
  </div>

  <div class="field">
    <%= f.hidden_field(:capa_cache) %>
  </div>

  <div class="field">
    <%= f.label :capa %> <br>
    <%= f.file_field :capa %>

  </div>


  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/livros/_menu.html.erb
<table>
  <tr>
    <td> <%= link_to "Livros", livros_path %>  || </td>
    <td> <%= link_to "Paginas", pages_path %> </td>
  </tr>
</table>

app/views/livros/edit.html.erb
<h1>Editando livro</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @livro %> |
<%= link_to 'Voltar', livros_path %>

app/views/livros/home.html.erb
<%= form_tag @pages, new_page_path do %>

<div class="field">
  <%= select_tag :livro_id, options_from_collection_for_select(Livro.all, :id, :titulo) %>
</div>

<div class="actions">
  <%= submit_tag "Enviar" %>
</div>

<% end %>

app/views/livros/index.html.erb
    <h1>Livros</h1>

    <table cellspacing="5" cellpadding="5">
      <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
        <% @livros.each do |livro| %>
                <td>
                <td><%= link_to( image_tag(livro.capa_url, :width => 150, :height => 150),livro.capa_url) if livro.capa? %> </td>
                <td valign="top"> Titulo: <%= livro.titulo %> <br>
                  Autor: <%= livro.autor %> <br>
                  Editora: <%= livro.editora %> <br> <br>
                  <%= link_to 'Mostrar', livro %> <br><br>
                  <%= link_to 'Editar', edit_livro_path(livro) %></br> <br>
                  <%= link_to 'Apagar', livro, method: :delete, data: { confirm: 'Tem certeza?' } %>
                </td></tr>
            <% end %>
     </tbody>

    </table>
    <br>

    <%= link_to 'Novo Livro', new_livro_path %>

    <%= paginate @livros  %>

app/views/livros/new.html.erb
<h1>Novo livro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', livros_path %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Editora:</strong>
  <%= @livro.editora %>
</p>

<%= link_to 'Editar', edit_livro_path(@livro) %> |
<%= link_to 'Voltar', livros_path %>

app/views/pages/_form.html.erb
<script language="javascript">
  $(function() {
      $(".datepicker").datepicker({
          format: "dd/mm/yyyy",
          language: 'pt-BR'
      })
  })
</script>



<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
   Escolha o livro:<br>
   <%= f.select :livro_id, options_from_collection_for_select(Livro.all, :id, :titulo, selected: f.object.livro_id),include_blank:true  %>

  </div>

  <div class="field">
    <%= f.label :data %> <br>
    <%= f.text_field :data, class: 'datepicker' %>     <!--, value: Date.today, readonly: true %> -->
  </div>

  <div class="field">
    <%= f.label :pagina %><br>
    <%= f.text_field :pagina %>
  </div>

   <div clas="field">
     <%= f.check_box(:livrocompleto) %>
     <%= f.label(:livrocompleto, "Leitura concuída") %>
   </div>

  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/pages/_menu.html.erb
<table>
  <tr>
    <td> <%= link_to "Livros", livros_path %>  || </td>
    <td> <%= link_to "Paginas", pages_path %> </td>
  </tr>
</table>

app/views/pages/edit.html.erb
<h1>Marcar páginas</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @page %> |
<%= link_to 'Voltar', pages_path %>

app/views/pages/index.html.erb
<h1> Marcador de páginas </h1>

<table cellspacing="5" cellpadding="5">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td valign="top"><%= link_to(image_tag(page.livro.capa_url, :width => 150, :height => 150),page.livro.capa_url) if page.livro.capa? %></td>
        <td>Data:  <%= page.data %> <br>
        <% if page.livrocompleto == true %>
              Livro concluído  <br> <br>
        <% else %>
              Última página lida: <%= page.pagina %> <br> <br>
        <% end %>
        <%= link_to 'Mostrar', page %> <br> <br>
        <%= link_to 'Editar', edit_page_path(page) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Escolher outro livro', new_page_path %>

<%= paginate @pages %>

app/views/pages/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> Livro</strong>
  <%= @page.livro.titulo %>
</p>

<p>
  <strong>Data:</strong>
  <%=@page.data  %>
</p>

<% if @page.livrocompleto == true %>
    <p>Livro concluído  </p>
<% else %>
    <p>
        <strong>Ultima Pagina Lida:</strong>
        <%= @page.pagina %>
    </p>
<% end %>
<%= link_to 'Editar', edit_page_path(@page) %> |
<%= link_to 'Voltar', pages_path %>